[package]
name = "aps-harvesting_procedures"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
rosetta_uuid.workspace = true
aps-assets.workspace = true
aps-harvesting_procedure_templates.workspace = true
aps-procedure_asset_models.workspace = true
aps-procedure_template_asset_models.workspace = true
aps-procedures.workspace = true
aps-sample_models.workspace = true
aps-sample_source_models.workspace = true
aps-sample_sources.workspace = true
aps-samples.workspace = true

[lints]
workspace = true
