[package]
name = "aps-taxon_names"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
validation-errors.workspace = true
rosetta-uuid.workspace = true
aps-entities.workspace = true
aps-name_classes.workspace = true
aps-organism_taxa.workspace = true
aps-organism_taxonomies.workspace = true

[lints]
workspace = true
