[package]
name = "aps-photographs"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
rosetta_uuid.workspace = true
aps-assets.workspace = true
aps-digital_assets.workspace = true

[lints]
workspace = true
