[package]
name = "procedure-template-visitor"
version = "0.1.0"
edition.workspace = true

[dependencies]
geometric-traits = { git = "https://github.com/earth-metabolome-initiative/geometric-traits" }
diesel.workspace = true
diesel-builders.workspace = true
rosetta-uuid.workspace = true
thiserror = "2.0"
aps-test-utils.workspace = true
aps-procedure_templates.workspace = true
aps-procedure_template_asset_models.workspace = true
aps-asset_models.workspace = true
aps-parent_procedure_templates.workspace = true
aps-next_procedure_templates.workspace = true
aps-users.workspace = true
aps-ownables.workspace = true
aps-namespaced_ownables.workspace = true
aps-procedure_asset_models.workspace = true
aps-procedures.workspace = true
aps-reused_procedure_template_asset_models.workspace = true
validation-errors.workspace = true
aps-entities.workspace = true
procedure-like.workspace = true
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2"

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
serial_test = "3.0"

[lints]
workspace = true
