[package]
name = "aps-procedure_template_asset_models"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
validation_errors.workspace = true
rosetta_uuid.workspace = true
aps-asset_models.workspace = true
aps-procedure_templates.workspace = true

[lints]
workspace = true
