[package]
name = "aps-storage_procedures"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
validation-errors.workspace = true
rosetta-uuid.workspace = true
aps-asset_compatibility_rules.workspace = true
aps-assets.workspace = true
aps-container_models.workspace = true
aps-containers.workspace = true
aps-entities.workspace = true
aps-ownables.workspace = true
aps-physical_asset_models.workspace = true
aps-physical_assets.workspace = true
aps-procedure_asset_models.workspace = true
aps-procedure_template_asset_models.workspace = true
aps-procedures.workspace = true
aps-storage_procedure_templates.workspace = true
procedure-like = { path = "../../crates/procedure-like" }

[lints]
workspace = true
