[package]
name = "procedure-traits"
version = "0.1.0"
edition.workspace = true

[dependencies]
aps-procedure_templates.workspace = true
aps-users.workspace = true
aps-next_procedure_templates.workspace = true
aps-parent_procedure_templates.workspace = true
aps-procedure_template_asset_models.workspace = true
aps-asset_models.workspace = true
aps-reused_procedure_template_asset_models.workspace = true
diesel-builders.workspace = true
diesel.workspace = true

[dev-dependencies]
aps-test-utils.workspace = true

[lints]
workspace = true
