[package]
name = "aps-traits"
version = "0.1.0"
edition.workspace = true

[dependencies]
aps-asset_models.workspace = true
aps-entities.workspace = true
aps-container_models.workspace = true
aps-namespaced_ownables.workspace = true
aps-next_procedure_templates.workspace = true
aps-parent_procedure_templates.workspace = true
aps-procedure_template_asset_models.workspace = true
aps-procedure_templates.workspace = true
aps-reused_procedure_template_asset_models.workspace = true
aps-users.workspace = true
aps-physical_asset_models.workspace = true
aps-container_compatibility_rules.workspace = true
aps-asset_compatibility_rules.workspace = true
aps-ownables.workspace = true
diesel-builders.workspace = true
validation-errors.workspace = true
diesel.workspace = true

[dev-dependencies]
aps-test-utils = { path = "../aps-test-utils" }
aps-namespaces.workspace = true
aps-pipette_tip_models.workspace = true

[lints]
workspace = true
