[package]
name = "aps-owner_grants"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
validation-errors.workspace = true
rosetta-uuid.workspace = true
aps-owners.workspace = true
aps-roles.workspace = true

[lints]
workspace = true
