[package]
name = "procedure-template-visualization"
version = "0.1.0"
edition.workspace = true

[dependencies]
mermaid-builder.workspace = true
diesel.workspace = true
guided_procedures.workspace = true

[lints]
workspace = true
