[package]
name = "aps"
version = "0.1.0"
edition.workspace = true


[dependencies]
aps-aliquoting_procedure_templates.workspace = true
aps-aliquoting_procedures.workspace = true
aps-asset_compatibility_rules.workspace = true
aps-asset_model_ancestors.workspace = true
aps-asset_models.workspace = true
aps-assets.workspace = true
aps-ball_mill_machine_models.workspace = true
aps-ball_mill_machines.workspace = true
aps-ball_mill_procedure_templates.workspace = true
aps-ball_mill_procedures.workspace = true
aps-bead_models.workspace = true
aps-brands.workspace = true
aps-camera_models.workspace = true
aps-cameras.workspace = true
aps-centrifuge_models.workspace = true
aps-centrifuge_procedure_templates.workspace = true
aps-centrifuge_procedures.workspace = true
aps-centrifuges.workspace = true
aps-commercial_ball_mill_machine_lots.workspace = true
aps-commercial_ball_mill_machine_models.workspace = true
aps-commercial_camera_lots.workspace = true
aps-commercial_camera_models.workspace = true
aps-commercial_centrifuge_lots.workspace = true
aps-commercial_centrifuge_models.workspace = true
aps-commercial_freeze_dryer_lots.workspace = true
aps-commercial_freeze_dryer_models.workspace = true
aps-commercial_freezer_lots.workspace = true
aps-commercial_freezer_models.workspace = true
aps-commercial_geopositioning_device_lots.workspace = true
aps-commercial_geopositioning_device_models.workspace = true
aps-commercial_product_lots.workspace = true
aps-commercial_products.workspace = true
aps-container_compatibility_rules.workspace = true
aps-container_models.workspace = true
aps-container_sealer_models.workspace = true
aps-container_sealing_procedure_templates.workspace = true
aps-container_sealing_procedures.workspace = true
aps-containers.workspace = true
aps-digital_asset_models.workspace = true
aps-digital_assets.workspace = true
aps-disposal_procedure_templates.workspace = true
aps-disposal_procedures.workspace = true
aps-entities.workspace = true
aps-fractioning_procedure_templates.workspace = true
aps-fractioning_procedures.workspace = true
aps-freeze_dryer_models.workspace = true
aps-freeze_dryers.workspace = true
aps-freeze_drying_procedure_templates.workspace = true
aps-freeze_drying_procedures.workspace = true
aps-freezer_models.workspace = true
aps-freezers.workspace = true
aps-freezing_procedure_templates.workspace = true
aps-freezing_procedures.workspace = true
aps-geopositioning_device_models.workspace = true
aps-geopositioning_devices.workspace = true
aps-geopositioning_procedure_templates.workspace = true
aps-geopositioning_procedures.workspace = true
aps-harvesting_procedure_templates.workspace = true
aps-harvesting_procedures.workspace = true
aps-namespaced_ownables.workspace = true
aps-namespaces.workspace = true
aps-next_procedure_templates.workspace = true
aps-ownables.workspace = true
aps-owner_grants.workspace = true
aps-owners.workspace = true
aps-packaging_models.workspace = true
aps-packaging_procedure_templates.workspace = true
aps-packaging_procedures.workspace = true
aps-parent_procedure_templates.workspace = true
aps-personal_protective_equipment_models.workspace = true
aps-personal_protective_equipments.workspace = true
aps-photograph_procedure_templates.workspace = true
aps-photograph_procedures.workspace = true
aps-photographs.workspace = true
aps-physical_asset_models.workspace = true
aps-physical_assets.workspace = true
aps-pouring_procedure_templates.workspace = true
aps-pouring_procedures.workspace = true
aps-privacy_dependencies.workspace = true
aps-procedure_asset_models.workspace = true
aps-procedure_template_asset_models.workspace = true
aps-procedure_templates.workspace = true
aps-procedures.workspace = true
aps-reused_procedure_template_asset_models.workspace = true
aps-roles.workspace = true
aps-sample_models.workspace = true
aps-sample_source_models.workspace = true
aps-sample_sources.workspace = true
aps-samples.workspace = true
aps-storage_procedure_templates.workspace = true
aps-storage_procedures.workspace = true
aps-supernatant_procedure_templates.workspace = true
aps-supernatant_procedures.workspace = true
aps-table_names.workspace = true
aps-team_members.workspace = true
aps-teams.workspace = true
aps-tombstones.workspace = true
aps-users.workspace = true
aps-volume_measuring_device_models.workspace = true
aps-volume_measuring_devices.workspace = true
aps-volumetric_container_models.workspace = true
aps-volumetric_containers.workspace = true
aps-weighed_container_models.workspace = true
aps-weighing_device_models.workspace = true
aps-weighing_devices.workspace = true
aps-weighing_procedure_templates.workspace = true
aps-weighing_procedures.workspace = true

[lints]
workspace = true
