[package]
name = "aps-next_procedure_templates"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
validation-errors.workspace = true
rosetta-uuid.workspace = true
aps-entities.workspace = true
aps-ownables.workspace = true
aps-parent_procedure_templates.workspace = true
aps-procedure_templates.workspace = true

[lints]
workspace = true
